import {Cafe} from "./cafe";

export const cafelist: Cafe [] = [
    {name: 'Kafein',
        distance: '0.1',
        status: 'red',
        shape: 'radio-button-on',
        hours: '6:30 AM - 6:00 PM',},
    {name: 'Peet\'s Coffee',
        distance: '0.1',
        status: 'green',
        shape: 'radio-button-on',
        hours: '6:30 AM - 6:00 PM',},
    {name: 'Unicorn',
        distance: '0.2',
        status: 'green',
        shape: 'radio-button-on',
        hours: '6:30 AM - 6:00 PM',},
    {name: 'Cupitol',
        distance: '0.5',
        status: 'orange',
        shape: 'radio-button-on',
        hours: '6:30 AM - 6:00 PM',},
    {name: 'Sherbucks',
        distance: '0.8',
        status: 'red',
        shape: 'radio-button-on',
        hours: '6:30 AM - 6:00 PM',},
    {name: 'Norbucks',
        distance: '1.2',
        status: 'green',
        shape: 'radio-button-on',
        hours: '6:30 AM - 6:00 PM',},
    {name: 'Cafe Bergson',
        distance: '1.7',
        status: 'orange',
        shape: 'radio-button-on',
        hours: '6:30 AM - 6:00 PM',},
    {name: 'Einstein\s Bagels',
        distance: '2.4',
        status: 'red',
        shape: 'radio-button-on',
        hours: '6:30 AM - 6:00 PM',},

];